# Generated by Django 6.1 on 2026-08-10 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='About Us', max_length=100)),
                ('heading', models.CharField(default='Best Medical Care For Yourself and Your Family', max_length=200)),
                ('description', models.TextField(blank=True, default='IHeartCare is committed to providing personalized, family-centered healthcare with compassion and expertise.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fa-user-md', help_text='Font Awesome icon class, e.g. "fa-user-md"', max_length=60)),
                ('title', models.CharField(help_text='Top line, e.g. "Qualified"', max_length=50)),
                ('subtitle', models.CharField(help_text='Bottom line, e.g. "Doctors"', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.aboutpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
