# Generated by Django 6.1 on 2026-08-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutpage_aboutfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
    ]
