# Generated by Django 5.2.15 on 2026-08-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_doctor_department_doctor_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('source', models.CharField(choices=[('upload', 'Uploaded Video'), ('youtube', 'YouTube Link')], default='youtube', max_length=10)),
                ('video_file', models.FileField(blank=True, help_text="Required when source is 'Uploaded Video'.", null=True, upload_to='gallery/videos/')),
                ('youtube_url', models.URLField(blank=True, help_text="Required when source is 'YouTube Link', e.g. https://www.youtube.com/watch?v=XXXXXXX")),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional cover image. YouTube videos use the official thumbnail automatically if left blank.', null=True, upload_to='gallery/video_thumbs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Video',
                'verbose_name_plural': 'Gallery Videos',
                'ordering': ['order', '-id'],
            },
        ),
    ]
