# Generated by Django 5.2.15 on 2026-08-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_galleryphoto_galleryvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
